
import { Lightbulb } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

export function InsightsView() {
  return (
    <Card>
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <Lightbulb className="h-5 w-5 text-primary" />
          Key Insights
        </CardTitle>
      </CardHeader>
      <CardContent className="space-y-2">
        <p className="text-muted-foreground">Actionable insights generated by the AI will be displayed here.</p>
        <p className="text-sm text-blue-400">Connecting to Gemini for analysis...</p>
      </CardContent>
    </Card>
  );
}
